name: Assign PR team labels
on:
  pull_request:
    branches:
      - main
      - release/current
permissions:
  contents: read
  pull-requests: write
jobs:
  auto-label:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Label
        uses: FiligranHQ/filigran-ci-tools/actions/auto-label@main
        with:
          labels_by_organization: '{"FiligranHQ":["filigran team"]}'
