name: Assign PR team labels
on:
  pull_request:
    branches:
      - main
      - release/current
jobs:
  auto-label:
    runs-on: ubuntu-latest
    steps:
      - name: Auto Label
        uses: guillaumejparis/ci-tools/actions/auto-label@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels_by_organization: '{"FiligranHQ":["filigran team"]}'
